#!/bin/bash
cd ../../res

for distro in $(cat distrolist);do
    echo $distro
    mkdir $distro
    cd $distro
    wget distrowatch.com/$distro -O index.html
    pwd
    logo_url=$(python ../../filter_logo_url/filter_logo_url.py index.html)
    wget $logo_url -O logo.png
    rm index.html
    cd ..
done
